export const TOGGLE_BURGER = 'TOGGLE_BURGER'
export const TOGGLE_DARK_MODE = 'TOGGLE_DARK_MODE'

export const FETCH_PROVINCE_REQ = 'FETCH_PROVINCE_REQ'
export const FETCH_PROVINCE_SUCCESS = 'FETCH_PROVINCE_SUCCESS'
export const FETCH_PROVINCE_ERROR = 'FETCH_PROVINCE_ERROR'

export const FETCH_COUNTRY_REQ = 'FETCH_COUNTRY_REQ'
export const FETCH_COUNTRY_SUCCESS = 'FETCH_COUNTRY_SUCCESS'
export const FETCH_COUNTRY_ERROR = 'FETCH_COUNTRY_ERROR'

export const FETCH_SEARCH_REQ = 'FETCH_SEARCH_REQ'
export const FETCH_SEARCH_SUCCESS = 'FETCH_SEARCH_SUCCESS'
export const FETCH_SEARCH_ERROR = 'FETCH_SEARCH_ERROR'

export const LARGE_WINDOW_SIZE = 'LARGE_WINDOW_SIZE'
export const SMALL_WINDOW_SIZE = 'SMALL_WINDOW_SIZE'